const products = [
    // Clothing Items
    {
        id: 'c1',
        name: 'Classic Cotton T-Shirt',
        category: 'clothing',
        price: 2999,
        image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500&q=80',
        description: 'Premium cotton t-shirt with a comfortable fit. Perfect for everyday wear.',
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['Black', 'White', 'Navy', 'Gray'],
        inStock: true,
    },
    {
        id: 'c2',
        name: 'Denim Jacket',
        category: 'clothing',
        price: 8999,
        image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=500&q=80',
        description: 'Stylish denim jacket with a modern cut. A wardrobe essential.',
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['Light Blue', 'Dark Blue', 'Black'],
        inStock: true,
    },
    {
        id: 'c3',
        name: 'Casual Chinos',
        category: 'clothing',
        price: 5999,
        image: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=500&q=80',
        description: 'Comfortable chinos perfect for both casual and semi-formal occasions.',
        sizes: ['28', '30', '32', '34', '36'],
        colors: ['Khaki', 'Navy', 'Black', 'Olive'],
        inStock: true,
    },
    {
        id: 'c4',
        name: 'Hoodie Sweatshirt',
        category: 'clothing',
        price: 4999,
        image: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=500&q=80',
        description: 'Cozy hoodie with soft fleece lining. Perfect for cool weather.',
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        colors: ['Gray', 'Black', 'Navy', 'Burgundy'],
        inStock: true,
    },
    {
        id: 'c5',
        name: 'Formal Dress Shirt',
        category: 'clothing',
        price: 6999,
        image: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=500&q=80',
        description: 'Elegant dress shirt for professional and formal occasions.',
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['White', 'Light Blue', 'Pink'],
        inStock: true,
    },
    {
        id: 'c6',
        name: 'Leather Jacket',
        category: 'clothing',
        price: 19999,
        image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=500&q=80',
        description: 'Premium leather jacket with classic styling and superior quality.',
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['Black', 'Brown'],
        inStock: true,
    },
    
    // Watch Items
    {
        id: 'w1',
        name: 'Classic Chronograph',
        category: 'watch',
        price: 29999,
        image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500&q=80',
        description: 'Elegant chronograph watch with stainless steel case and leather strap.',
        inStock: true,
    },
    {
        id: 'w2',
        name: 'Sport Digital Watch',
        category: 'watch',
        price: 14999,
        image: 'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=500&q=80',
        description: 'Durable sport watch with digital display and water resistance.',
        inStock: true,
    },
    {
        id: 'w3',
        name: 'Minimalist Gold Watch',
        category: 'watch',
        price: 39999,
        image: 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=500&q=80',
        description: 'Sleek minimalist design with gold-tone finish and mesh band.',
        inStock: true,
    },
    {
        id: 'w4',
        name: 'Luxury Automatic',
        category: 'watch',
        price: 79999,
        image: 'https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?w=500&q=80',
        description: 'Premium automatic watch with sapphire crystal and exhibition caseback.',
        inStock: true,
    },
    {
        id: 'w5',
        name: 'Smart Fitness Watch',
        category: 'watch',
        price: 24999,
        image: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=500&q=80',
        description: 'Advanced fitness tracking with heart rate monitor and GPS.',
        inStock: true,
    },
    {
        id: 'w6',
        name: 'Vintage Pilot Watch',
        category: 'watch',
        price: 44999,
        image: 'https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?w=500&q=80',
        description: 'Classic pilot-style watch with large luminous hands and markers.',
        inStock: true,
    },
];